version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: vshu_db
      POSTGRES_USER: vshu
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
